// flow-typed signature: 8c40b7f97b1c9be87b47f8e85df9c0bf
// flow-typed version: <<STUB>>/gstore-node_v^4.2.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gstore-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gstore-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gstore-node/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'gstore-node/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/constants' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/dataloader' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/entity' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/errors' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/helpers/defaultValues' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/helpers/index' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/helpers/queryhelpers' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/helpers/validation' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/index' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/model' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/query' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/schema' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/serializer' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/serializers/datastore' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/utils' {
  declare module.exports: any;
}

declare module 'gstore-node/lib/virtualType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gstore-node/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'gstore-node/coverage/lcov-report/prettify'>;
}
declare module 'gstore-node/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'gstore-node/coverage/lcov-report/sorter'>;
}
declare module 'gstore-node/index' {
  declare module.exports: $Exports<'gstore-node'>;
}
declare module 'gstore-node/index.js' {
  declare module.exports: $Exports<'gstore-node'>;
}
declare module 'gstore-node/lib/constants.js' {
  declare module.exports: $Exports<'gstore-node/lib/constants'>;
}
declare module 'gstore-node/lib/dataloader.js' {
  declare module.exports: $Exports<'gstore-node/lib/dataloader'>;
}
declare module 'gstore-node/lib/entity.js' {
  declare module.exports: $Exports<'gstore-node/lib/entity'>;
}
declare module 'gstore-node/lib/errors.js' {
  declare module.exports: $Exports<'gstore-node/lib/errors'>;
}
declare module 'gstore-node/lib/helpers/defaultValues.js' {
  declare module.exports: $Exports<'gstore-node/lib/helpers/defaultValues'>;
}
declare module 'gstore-node/lib/helpers/index.js' {
  declare module.exports: $Exports<'gstore-node/lib/helpers/index'>;
}
declare module 'gstore-node/lib/helpers/queryhelpers.js' {
  declare module.exports: $Exports<'gstore-node/lib/helpers/queryhelpers'>;
}
declare module 'gstore-node/lib/helpers/validation.js' {
  declare module.exports: $Exports<'gstore-node/lib/helpers/validation'>;
}
declare module 'gstore-node/lib/index.js' {
  declare module.exports: $Exports<'gstore-node/lib/index'>;
}
declare module 'gstore-node/lib/model.js' {
  declare module.exports: $Exports<'gstore-node/lib/model'>;
}
declare module 'gstore-node/lib/query.js' {
  declare module.exports: $Exports<'gstore-node/lib/query'>;
}
declare module 'gstore-node/lib/schema.js' {
  declare module.exports: $Exports<'gstore-node/lib/schema'>;
}
declare module 'gstore-node/lib/serializer.js' {
  declare module.exports: $Exports<'gstore-node/lib/serializer'>;
}
declare module 'gstore-node/lib/serializers/datastore.js' {
  declare module.exports: $Exports<'gstore-node/lib/serializers/datastore'>;
}
declare module 'gstore-node/lib/utils.js' {
  declare module.exports: $Exports<'gstore-node/lib/utils'>;
}
declare module 'gstore-node/lib/virtualType.js' {
  declare module.exports: $Exports<'gstore-node/lib/virtualType'>;
}
