// flow-typed signature: 0e1255ccc5cd72ab7831e3333d49f2b5
// flow-typed version: <<STUB>>/requestify_v^0.2.5/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'requestify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'requestify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'requestify/lib/cache-transporters/in-memory-transporter' {
  declare module.exports: any;
}

declare module 'requestify/lib/cache-transporters/mongo-transporter' {
  declare module.exports: any;
}

declare module 'requestify/lib/cache-transporters/redis-transporter' {
  declare module.exports: any;
}

declare module 'requestify/lib/cache' {
  declare module.exports: any;
}

declare module 'requestify/lib/interface-validator' {
  declare module.exports: any;
}

declare module 'requestify/lib/logger-adapters/console-adapter' {
  declare module.exports: any;
}

declare module 'requestify/lib/logger-adapters/winston-adapter' {
  declare module.exports: any;
}

declare module 'requestify/lib/logger' {
  declare module.exports: any;
}

declare module 'requestify/lib/request' {
  declare module.exports: any;
}

declare module 'requestify/lib/requestify' {
  declare module.exports: any;
}

declare module 'requestify/lib/response' {
  declare module.exports: any;
}

declare module 'requestify/test/cache-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/cache-transporters/in-memory-transporter-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/cache-transporters/mongo-transporter-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/cache-transporters/redis-trasporter-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/interface-validator-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/logger-adapters/console-adapter-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/logger-adapters/winston-adapter-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/logger-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/request-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/requestify-spec' {
  declare module.exports: any;
}

declare module 'requestify/test/response-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'requestify/index' {
  declare module.exports: $Exports<'requestify'>;
}
declare module 'requestify/index.js' {
  declare module.exports: $Exports<'requestify'>;
}
declare module 'requestify/lib/cache-transporters/in-memory-transporter.js' {
  declare module.exports: $Exports<'requestify/lib/cache-transporters/in-memory-transporter'>;
}
declare module 'requestify/lib/cache-transporters/mongo-transporter.js' {
  declare module.exports: $Exports<'requestify/lib/cache-transporters/mongo-transporter'>;
}
declare module 'requestify/lib/cache-transporters/redis-transporter.js' {
  declare module.exports: $Exports<'requestify/lib/cache-transporters/redis-transporter'>;
}
declare module 'requestify/lib/cache.js' {
  declare module.exports: $Exports<'requestify/lib/cache'>;
}
declare module 'requestify/lib/interface-validator.js' {
  declare module.exports: $Exports<'requestify/lib/interface-validator'>;
}
declare module 'requestify/lib/logger-adapters/console-adapter.js' {
  declare module.exports: $Exports<'requestify/lib/logger-adapters/console-adapter'>;
}
declare module 'requestify/lib/logger-adapters/winston-adapter.js' {
  declare module.exports: $Exports<'requestify/lib/logger-adapters/winston-adapter'>;
}
declare module 'requestify/lib/logger.js' {
  declare module.exports: $Exports<'requestify/lib/logger'>;
}
declare module 'requestify/lib/request.js' {
  declare module.exports: $Exports<'requestify/lib/request'>;
}
declare module 'requestify/lib/requestify.js' {
  declare module.exports: $Exports<'requestify/lib/requestify'>;
}
declare module 'requestify/lib/response.js' {
  declare module.exports: $Exports<'requestify/lib/response'>;
}
declare module 'requestify/test/cache-spec.js' {
  declare module.exports: $Exports<'requestify/test/cache-spec'>;
}
declare module 'requestify/test/cache-transporters/in-memory-transporter-spec.js' {
  declare module.exports: $Exports<'requestify/test/cache-transporters/in-memory-transporter-spec'>;
}
declare module 'requestify/test/cache-transporters/mongo-transporter-spec.js' {
  declare module.exports: $Exports<'requestify/test/cache-transporters/mongo-transporter-spec'>;
}
declare module 'requestify/test/cache-transporters/redis-trasporter-spec.js' {
  declare module.exports: $Exports<'requestify/test/cache-transporters/redis-trasporter-spec'>;
}
declare module 'requestify/test/interface-validator-spec.js' {
  declare module.exports: $Exports<'requestify/test/interface-validator-spec'>;
}
declare module 'requestify/test/logger-adapters/console-adapter-spec.js' {
  declare module.exports: $Exports<'requestify/test/logger-adapters/console-adapter-spec'>;
}
declare module 'requestify/test/logger-adapters/winston-adapter-spec.js' {
  declare module.exports: $Exports<'requestify/test/logger-adapters/winston-adapter-spec'>;
}
declare module 'requestify/test/logger-spec.js' {
  declare module.exports: $Exports<'requestify/test/logger-spec'>;
}
declare module 'requestify/test/request-spec.js' {
  declare module.exports: $Exports<'requestify/test/request-spec'>;
}
declare module 'requestify/test/requestify-spec.js' {
  declare module.exports: $Exports<'requestify/test/requestify-spec'>;
}
declare module 'requestify/test/response-spec.js' {
  declare module.exports: $Exports<'requestify/test/response-spec'>;
}
