// flow-typed signature: 761984e5218a75fc078b6d3404555990
// flow-typed version: <<STUB>>/@google-cloud/debug-agent_v^2.5.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/debug-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/debug-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/debug-agent/build/src/agent/config' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/controller' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/debuglet' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/io/scanner' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/io/sourcemapper' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/state/inspector-state' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/state/legacy-state' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/util/debug-assert' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/util/utils' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/util/validator' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/v8/debugapi' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/v8/inspector-debugapi' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/v8/legacy-debugapi' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/agent/v8/v8inspector' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/client/stackdriver/debug' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/client/stackdriver/status-message' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/debuggee' {
  declare module.exports: any;
}

declare module '@google-cloud/debug-agent/build/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/debug-agent/build/src/agent/config.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/config'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/controller.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/controller'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/debuglet.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/debuglet'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/io/scanner.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/io/scanner'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/io/sourcemapper.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/io/sourcemapper'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/state/inspector-state.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/state/inspector-state'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/state/legacy-state.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/state/legacy-state'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/util/debug-assert.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/util/debug-assert'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/util/utils.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/util/utils'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/util/validator.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/util/validator'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/v8/debugapi.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/v8/debugapi'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/v8/inspector-debugapi.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/v8/inspector-debugapi'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/v8/legacy-debugapi.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/v8/legacy-debugapi'>;
}
declare module '@google-cloud/debug-agent/build/src/agent/v8/v8inspector.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/agent/v8/v8inspector'>;
}
declare module '@google-cloud/debug-agent/build/src/client/stackdriver/debug.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/client/stackdriver/debug'>;
}
declare module '@google-cloud/debug-agent/build/src/client/stackdriver/status-message.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/client/stackdriver/status-message'>;
}
declare module '@google-cloud/debug-agent/build/src/debuggee.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/debuggee'>;
}
declare module '@google-cloud/debug-agent/build/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/debug-agent/build/src/index'>;
}
