// flow-typed signature: 0864e9ec83416dd46d4949c5e3f42d61
// flow-typed version: <<STUB>>/@google-cloud/logging-winston_v^0.9.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/logging-winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/logging-winston' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/logging-winston/build/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/logging-winston/build/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/logging-winston/build/src/index'>;
}
