// flow-typed signature: e6019529743767198879a771841358ea
// flow-typed version: <<STUB>>/@google-cloud/trace-agent_v^2.7.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/trace-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/trace-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/trace-agent/build/src/cls-ah' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/cls' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/config' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/constants' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/index' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugin-types' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-connect' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-express' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-generic-pool' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-grpc' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-hapi' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-http' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-http2' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-knex' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-koa' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-mongodb-core' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-mysql' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-mysql2' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-pg' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-redis' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/plugins/plugin-restify' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/span-data' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/trace-api' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/trace-labels' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/trace-plugin-loader' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/trace-writer' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/trace' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/tracing-policy' {
  declare module.exports: any;
}

declare module '@google-cloud/trace-agent/build/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/trace-agent/build/src/cls-ah.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/cls-ah'>;
}
declare module '@google-cloud/trace-agent/build/src/cls.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/cls'>;
}
declare module '@google-cloud/trace-agent/build/src/config.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/config'>;
}
declare module '@google-cloud/trace-agent/build/src/constants.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/constants'>;
}
declare module '@google-cloud/trace-agent/build/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/index'>;
}
declare module '@google-cloud/trace-agent/build/src/plugin-types.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugin-types'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-connect.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-connect'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-express.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-express'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-generic-pool.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-generic-pool'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-grpc.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-grpc'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-hapi.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-hapi'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-http.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-http'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-http2.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-http2'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-knex.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-knex'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-koa.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-koa'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-mongodb-core.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-mongodb-core'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-mysql.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-mysql'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-mysql2.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-mysql2'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-pg.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-pg'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-redis.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-redis'>;
}
declare module '@google-cloud/trace-agent/build/src/plugins/plugin-restify.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/plugins/plugin-restify'>;
}
declare module '@google-cloud/trace-agent/build/src/span-data.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/span-data'>;
}
declare module '@google-cloud/trace-agent/build/src/trace-api.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/trace-api'>;
}
declare module '@google-cloud/trace-agent/build/src/trace-labels.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/trace-labels'>;
}
declare module '@google-cloud/trace-agent/build/src/trace-plugin-loader.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/trace-plugin-loader'>;
}
declare module '@google-cloud/trace-agent/build/src/trace-writer.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/trace-writer'>;
}
declare module '@google-cloud/trace-agent/build/src/trace.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/trace'>;
}
declare module '@google-cloud/trace-agent/build/src/tracing-policy.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/tracing-policy'>;
}
declare module '@google-cloud/trace-agent/build/src/util.js' {
  declare module.exports: $Exports<'@google-cloud/trace-agent/build/src/util'>;
}
